#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 29 15:19:29 2024

@author: administrator
"""

import neurokit2 as nk
import numpy as np
import pandas as pd

def get_rris(pks, sf):
    # Find and correct RR intervals. Default is 400 ms (150 bpm) to 2000 ms (30 bpm)
    rr_limit=(400, 2000)
    rri = 1000 * np.diff(pks) / sf
    rri = np.ma.masked_outside(rri, rr_limit[0], rr_limit[1]).filled(np.nan)
    # Interpolate NaN values, but no more than 10 consecutive values
    if np.isnan(rri).any():
        rri = pd.Series(rri).interpolate(limit_direction="both", limit=10).to_numpy()
    if np.isnan(rri).any():
        # still NaN present?
        print("WARNING : Invalid RR intervals!")
    
    return rri

def ecg_power(peaks, sampling_rate):
    rri = get_rris(peaks, sampling_rate)
    power = nk.signal_power(
        rri,
        frequency_band=[(0, 50)],
        sampling_rate=sampling_rate,
        method="welch",
        max_frequency=100,
        show=True,
        continuous=False,
    )
    
    return power 

# nk.hrv_frequency(pks, kwargs)

#%%

from neurokit2.hrv import hrv_utils, intervals_process

# Step 1: Get ECG data and detect R-peaks
ecg_signal = nk.data("bio_resting_5min_100hz")['ECG']
peaks, info = nk.ecg_peaks(ecg_signal, sampling_rate=100)

# Step 2: Compute RR intervals (this step is handled by hrv_frequency but shown here for clarity)
rri, rri_time, sampling_rate = hrv_utils._hrv_format_input(peaks, sampling_rate=100)

# Step 3: Interpolate RR intervals to a consistent sampling rate
rri, rri_time, sampling_rate = intervals_process(
    rri, intervals_time=rri_time, interpolate=True, interpolation_rate=100
)

# Step 4: Compute the PSD using Welch's method (or any other method you prefer)
power = nk.signal_psd(rri, sampling_rate=100, method="welch", max_frequency=0.5)

 


# Step 2: Use nk.hrv_frequency to calculate HRV metrics and plot
hrv_results = nk.hrv_frequency(peaks, sampling_rate=100, show=True, psd_method="welch")

# Since nk.hrv_frequency handles interpolation and everything, you can focus on the output
# You can access the clean plot automatically generated by setting `show=True`

# If you need access to the PSD and frequencies, you'll need to capture it before the plot is generated:
rri, rri_time, sampling_rate = hrv_utils._hrv_format_input(peaks, sampling_rate=100)
rri, rri_time, sampling_rate = intervals_process(
    rri, intervals_time=rri_time, interpolate=True, interpolation_rate=100
)
power = nk.signal_psd(rri, sampling_rate=sampling_rate, method="welch", max_frequency=0.5)

# Now `psd` and `freqs` hold the power spectral density values and the corresponding frequencies.
print("Frequencies:", freqs)
print("PSD:", psd)