# -*- coding: utf-8 -*-
"""
Created on Mon Feb 17 09:36:25 2020

@author: neuro
"""
from os import chdir
import liesl
import reiz.marker
from sleepstim.core.stimulation import PinkNoise
import matplotlib.pyplot as plt
from reiz import clock
import numpy as np
import threading
from scipy import signal

#from reiz import clock
#%% set parameters
#%% fake EEG data stream can be generated by opening the terminal with liesl mock -type EEG
#%% maxamp needs to be set to an appropriate value
maxamp = 1
winshift_in_ms = 20

#%% set up EEG and marker stream
#-----------------------------
#----Tip: for development and testing, you can just set up a fake EEG stream by
#----entering the following into your command line:
#----liesl mock -type EEG
sinfo = liesl.get_streaminfos_matching(type = 'EEG')
bfr = liesl.RingBuffer(sinfo[0], duration_in_ms = 30000) #30 s buffer to allow sleep staging
bfr.start()

bfr.await_running()


#%% set up pink noise generator
n = PinkNoise()
volume = 1
n.samples = n.samples * volume


#%% build sleep staging function
def some_classifier(d): #this is just a toy example, will be replaced by your classifier later on
    if int(d[0,0]*100000)%2 == 0:
        stage = 0
    else:
        stage = 1
    return stage

#this returns sleep stage as a global variable. Not the most elegant way of doing this, but it works for now
def sleep_staging(bfr):
    while True:
        d = bfr.get_data()
        global sleep_stage
        sleep_stage = some_classifier(d)
        print(sleep_stage)

        reiz.clock.sleep(15) #data will be pulled every ~15s

#%% put sleep stager into separate thread that can run in the background
sleep_stager = threading.Thread(target = sleep_staging, args = (bfr,))
sleep_stager.start()


winshift_in_ms = 20
winshift_in_samples = int((winshift_in_ms/1000)*sinfo.nominal_srate())
block_auditory_stim = False
tblock = 0
for interval in range(10000):
    if sleep_stage == 1: #we need to build something that detects whether the last n epochs were slow wave sleep.
        if clock.now() -tblock > 1.9:
            block_auditory_stim = False
            
            #%% proper channel needs to be picked here
        d = bfr.get_data()[:,1] 
        
        #%% online data preprocessing needs to be added here
        
        
        if max(d[-2:]) > maxamp * .9 and block_auditory_stim == False:
            n.play()
            block_auditory_stim = True
            tblock = clock.now()
    
        clock.sleep(winshift_in_ms/1000)
        
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
#TODO process EEG (filter? common avg. ref?)
# b,a = signal.butter(4, (.5, 1.5), btype = 'bandpass', fs = bfr.fs)
# t = signal.filtfilt(b,a,bfr.get_data(), axis = 0)

#TODO set up sleep stage classifier, gate SO detection
#TODO send marker
#TODO set up SO detection

#TODO block audio presentation for 2 s 
#set up a pink noise burst generator
#play sound burst
#tm = np.zeros(100)
#for tr in range(100):
#    n.play()
#    clock.sleep(.5)
